name: Docker

on:
  workflow_dispatch:
  push:
      paths-ignore:
        - "README.md"
      branches:
        - pre_guest_accounts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository}}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push AMD64 Docker image
        uses: docker/build-push-action@v5
        with:
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cache,mode=max
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cache
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          user: ${{ github.repository_owner }}
          container: nitter
          prune-untagged: true
          keep-last: 2
